// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("Elders.Cronus.Serialization.Proteus")]
[assembly: AssemblyDescriptionAttribute("Elders.Cronus.Serialization.Proteus")]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyProductAttribute("Elders.Cronus.Serialization.Proteus")]
[assembly: AssemblyCopyrightAttribute("Copyright ©  2016")]
[assembly: AssemblyVersionAttribute("2.0.3.0")]
[assembly: AssemblyFileVersionAttribute("2.0.3.0")]
[assembly: AssemblyInformationalVersionAttribute("2.0.3+Branch.master.Sha.f23b0bf84b95352fb080177b104a0d86a58602e0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "2.0.3.0";
    }
}
