// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("Elders.Cronus.Serialization.Proteus")]
[assembly: AssemblyDescriptionAttribute("Elders.Cronus.Serialization.Proteus")]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyProductAttribute("Elders.Cronus.Serialization.Proteus")]
[assembly: AssemblyCopyrightAttribute("Copyright ©  2016")]
[assembly: AssemblyVersionAttribute("2.0.4.0")]
[assembly: AssemblyFileVersionAttribute("2.0.4.0")]
[assembly: AssemblyInformationalVersionAttribute("2.0.4+1.Branch.master.Sha.41d9351adadfabbea5f17cfc03a9adf6d549a3a5")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "2.0.4.0";
    }
}
